version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nextjs-app
    ports:
      - '3000:3000'
    depends_on:
      - dev-db
    environment:
      DATABASE_URL: 'postgresql://travel_user:travel_admin@dev-db:5432/ai_travel'
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - ./backend/src:/app/backend/src
      - ./backend/prisma:/app/backend/prisma
    working_dir: /app/frontend
    tty: true
    stdin_open: true

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: hono-api
    ports:
      - '8787:8787'
    depends_on:
      - dev-db
    environment:
      DATABASE_URL: 'postgresql://travel_user:travel_admin@dev-db:5432/ai_travel'
      WATCHPACK_POLLING: true
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
      - ./prisma:/app/prisma
    working_dir: /app/backend
    tty: true
    stdin_open: true

  dev-db:
    container_name: postgres
    hostname: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'travel_user'
      POSTGRES_PASSWORD: 'travel_admin'
      POSTGRES_DB: 'ai_travel'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql
  test-db:
    container_name: postgres_test
    hostname: test-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'travel_user_test'
      POSTGRES_PASSWORD: 'travel_admin_test'
      POSTGRES_DB: 'ai_travel_test'
    ports:
      - '5433:5432'
    volumes:
      - postgres-test-data:/var/lib/postgresql

  prisma-studio:
    image: node:18-alpine
    container_name: prisma-studio
    ports:
      - '5555:5555'
    depends_on:
      - dev-db
    environment:
      DATABASE_URL: 'postgresql://travel_user:travel_admin@dev-db:5432/ai_travel'
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm install -g prisma && prisma studio --schema=./prisma/schema.prisma --port 5555 --hostname 0.0.0.0"

volumes:
  postgres-data:
  postgres-test-data:
